name: CI

on: [push, pull_request]

# Sets permissions of the GITHUB_TOKEN to allow deployment
permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout commy
        uses: actions/checkout@v2
        with:
          path: commy
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.13.0
      - name: Build
        run: zig build
        working-directory: commy

  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout commy
        uses: actions/checkout@v2
        with:
          path: commy
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.13.0
      - name: Build win
        working-directory: commy
        run: zig build -Dtarget=x86_64-windows
      - name: upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: zig-out/bin/commy.exe
          file_glob: true
          asset_name: windows
          overwrite: true
          body: "Windows binary"

