name: CI

on: [push, pull_request]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout commy
        uses: actions/checkout@v2
        with:
          path: commy
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.13.0
      - name: Build
        run: zig build
        working-directory: commy

